var level1 = { 
     
         "objects":[
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":224,
                 "y":232
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":160,
                 "y":102
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":735,
                 "y":199
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":735,
                 "y":199
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":736,
                 "y":71
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":799,
                 "y":135
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":862,
                 "y":135
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":831,
                 "y":200
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":321,
                 "y":259
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":416,
                 "y":323
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":416,
                 "y":323
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":67,
                         "y":2
                        }, 
                        {
                         "x":65,
                         "y":109
                        }, 
                        {
                         "x":-12,
                         "y":106
                        }, 
                        {
                         "x":-14,
                         "y":1
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":292,
                 "y":440
                }, 
                {
                 "height":0,
                 "name":"cactus",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":-2
                        }, 
                        {
                         "x":-8,
                         "y":-15
                        }, 
                        {
                         "x":-28,
                         "y":-14
                        }, 
                        {
                         "x":-27,
                         "y":-4
                        }, 
                        {
                         "x":-36,
                         "y":16
                        }, 
                        {
                         "x":-19,
                         "y":32
                        }, 
                        {
                         "x":0,
                         "y":27
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":192,
                 "y":292
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":136,
                         "y":-2
                        }, 
                        {
                         "x":129,
                         "y":37
                        }, 
                        {
                         "x":-15,
                         "y":37
                        }, 
                        {
                         "x":-11,
                         "y":0
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":166,
                 "y":383
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":245,
                         "y":-4
                        }, 
                        {
                         "x":234,
                         "y":32
                        }, 
                        {
                         "x":-9,
                         "y":33
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":387,
                 "y":546
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-1,
                         "y":18
                        }, 
                        {
                         "x":47,
                         "y":22
                        }, 
                        {
                         "x":47,
                         "y":-10
                        }, 
                        {
                         "x":-2,
                         "y":-9
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":572,
                 "y":585
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-60,
                         "y":64
                        }, 
                        {
                         "x":-49,
                         "y":172
                        }, 
                        {
                         "x":60,
                         "y":176
                        }, 
                        {
                         "x":137,
                         "y":256
                        }, 
                        {
                         "x":281,
                         "y":253
                        }, 
                        {
                         "x":304,
                         "y":-32
                        }, 
                        {
                         "x":23,
                         "y":-33
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":356,
                 "y":33
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-96,
                         "y":3
                        }, 
                        {
                         "x":-95,
                         "y":52
                        }, 
                        {
                         "x":-30,
                         "y":50
                        }, 
                        {
                         "x":-33,
                         "y":97
                        }, 
                        {
                         "x":-192,
                         "y":97
                        }, 
                        {
                         "x":-192,
                         "y":143
                        }, 
                        {
                         "x":35,
                         "y":142
                        }, 
                        {
                         "x":31,
                         "y":-435
                        }, 
                        {
                         "x":-923,
                         "y":-438
                        }, 
                        {
                         "x":-922,
                         "y":197
                        }, 
                        {
                         "x":34,
                         "y":197
                        }, 
                        {
                         "x":33,
                         "y":144
                        }, 
                        {
                         "x":2,
                         "y":142
                        }, 
                        {
                         "x":3,
                         "y":168
                        }, 
                        {
                         "x":-722,
                         "y":165
                        }, 
                        {
                         "x":-721,
                         "y":22
                        }, 
                        {
                         "x":-738,
                         "y":19
                        }, 
                        {
                         "x":-742,
                         "y":138
                        }, 
                        {
                         "x":-888,
                         "y":140
                        }, 
                        {
                         "x":-891,
                         "y":-407
                        }, 
                        {
                         "x":-124,
                         "y":-407
                        }, 
                        {
                         "x":-1,
                         "y":-295
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":924,
                 "y":438
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":33,
                         "y":2
                        }, 
                        {
                         "x":30,
                         "y":41
                        }, 
                        {
                         "x":-9,
                         "y":43
                        }, 
                        {
                         "x":-7,
                         "y":0
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":68,
                 "y":534
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":38
                        }, 
                        {
                         "x":38,
                         "y":39
                        }, 
                        {
                         "x":40,
                         "y":0
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":125,
                 "y":477
                }]
}