var level2 = {
         "objects":[
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":16,
                         "y":16
                        }, 
                        {
                         "x":33,
                         "y":-4
                        }, 
                        {
                         "x":46,
                         "y":14
                        }, 
                        {
                         "x":66,
                         "y":-4
                        }, 
                        {
                         "x":82,
                         "y":18
                        }, 
                        {
                         "x":98,
                         "y":-4
                        }, 
                        {
                         "x":108,
                         "y":12
                        }, 
                        {
                         "x":119,
                         "y":13
                        }, 
                        {
                         "x":126,
                         "y":37
                        }, 
                        {
                         "x":112,
                         "y":49
                        }, 
                        {
                         "x":95,
                         "y":62
                        }, 
                        {
                         "x":69,
                         "y":93
                        }, 
                        {
                         "x":48,
                         "y":88
                        }, 
                        {
                         "x":29,
                         "y":93
                        }, 
                        {
                         "x":13,
                         "y":84
                        }, 
                        {
                         "x":1,
                         "y":95
                        }, 
                        {
                         "x":-14,
                         "y":92
                        }, 
                        {
                         "x":-16,
                         "y":76
                        }, 
                        {
                         "x":-30,
                         "y":75
                        }, 
                        {
                         "x":-30,
                         "y":58
                        }, 
                        {
                         "x":-12,
                         "y":48
                        }, 
                        {
                         "x":-34,
                         "y":36
                        }, 
                        {
                         "x":-25,
                         "y":21
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":194,
                 "y":354
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":18,
                         "y":-5
                        }, 
                        {
                         "x":18,
                         "y":24
                        }, 
                        {
                         "x":-2,
                         "y":26
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":199,
                 "y":70
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":15,
                         "y":11
                        }, 
                        {
                         "x":15,
                         "y":30
                        }, 
                        {
                         "x":-12,
                         "y":30
                        }, 
                        {
                         "x":-12,
                         "y":13
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":334,
                 "y":32
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":8,
                         "y":8
                        }, 
                        {
                         "x":8,
                         "y":31
                        }, 
                        {
                         "x":-13,
                         "y":31
                        }, 
                        {
                         "x":-13,
                         "y":13
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":431,
                 "y":128
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":42,
                         "y":34
                        }, 
                        {
                         "x":44,
                         "y":63
                        }, 
                        {
                         "x":17,
                         "y":61
                        }, 
                        {
                         "x":17,
                         "y":31
                        }, 
                        {
                         "x":-13,
                         "y":29
                        }, 
                        {
                         "x":-14,
                         "y":9
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":531,
                 "y":193
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":26,
                         "y":-8
                        }, 
                        {
                         "x":33,
                         "y":0
                        }, 
                        {
                         "x":31,
                         "y":20
                        }, 
                        {
                         "x":10,
                         "y":24
                        }, 
                        {
                         "x":3,
                         "y":24
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":607,
                 "y":326
                }]}